### ISSUE TITLE
Material from object color not cached

### ISSUE THREAD

**Issue by visose** [mcneel/glTF-IO#14]
It looks like materials created using `CreateSolidColorMaterial` are not added to the material dictionary and reused for the same color.

I also suggest checking if the object is using the layer color with the default black color (255,0,0,0) and using the default material rather than a black material for these objects.

**Comment by jrz371** [comment]
Both good suggestions. I opened an issue in YouTrack
https://mcneel.myjetbrains.com/youtrack/issue/RH-72684/glTF-export-should-use-default-material-if-display-color-is-default-black
