### ISSUE TITLE
Inefficient conversion from mesh to byte arrays

### ISSUE THREAD

**Issue by visose** [mcneel/glTF-IO#16]
I'm getting a ~4x to 5x performance improvement with a couple changes in the `RhinoMeshGltfConverter` class:
1. You can turn a float array into a byte array in one go using `Buffer.BlockCopy`. The way it's currently done with `BitConverter.GetBytes` on each individual float and then using `SelectMany` is very inefficient.
2. Rhinocommon has `.To___Array` methods on all these mesh collections to create directly float arrays, int arrays, etc.

The code to get vertices would be:
```c#
var floats = vertices.ToFloatArray();
var bytes = new byte[floats.Length * 4];
Buffer.BlockCopy(floats, 0, bytes, 0, bytes.Length);
return bytes;
```

I would also suggest refactoring this class, there seems to be a lot of code that repeats itself, and might be cleaner to untangle the draco compression code from this class.

**Comment by jrz371** [comment]
Hi, thanks for the tip. I switched the SelectMany to Buffer.BlockCopy and things are faster. Also with PR #20 I added support for draco compression on point clouds. Unfortunately I don't think we can just use the to float array methods as min/max for the arrays still need calculated. I agree the class needs cleaned up but since its working I'm hesitant to refactor unless the code base is getting in the way of some other feature.

**Comment by visose** [comment]
You can easily calculate the min/max with the array methods. Use a simple for loop with increments of 2, 3 or 4 depending on the type.

**Comment by jrz371** [comment]
Yes, I have to iterate a collection anyway you look at it. I could knock out generic method to handle the float arrays with a stride but I'm not sure it's worth the effort at this time.

**Comment by visose** [comment]
Personally I would invest time refactoring this project. It can become more readable and performant in fewer lines of code. This is unusual, normally if you try to improve one of those, the other 2 suffer.

Something else I remember thinking of changing: Don't use a `List<byte>` and keep appending the buffers to it. Use a `List<byte[]>` (or `List<float[]>`) and join all the buffers once to a single array at the very end (without resizing).
